name: govsvc concourse-task-toolbox

on:
  push:
    branches:
      - 'master'
    paths:
      - 'reliability-engineering/dockerfiles/govsvc/oncourse-task-toolbox/**'

  workflow_dispatch:
    inputs:
      image_tag:
        description: "Tag used within docker repository to mark as unique"
        required: false
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repo
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # 2.4.0
      - uses: ./.github/shared/publish_to_docker
        with:
          docker_context: ./reliability-engineering/dockerfiles/govsvc/concourse-task-toolbox
          push_to_ghcr: true
          push_to_dockerhub: false
          ghcr_repo: ghcr.io/alphagov/automate/task-toolbox
          image_tag: ${{ github.context.inputs.image_tag }}
        # secrets:
          ghcr_username: ${{ secrets.GHCR_USERNAME }}
          ghcr_token: ${{ secrets.CHCR_TOKEN }}
                      